Models/CarrinhoCompraItem.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Lanchonete.Models
{
    [Table("CarrinhoCompraItens")]
    public class CarrinhoCompraItem
    {
        public int CarrinhoCompraItemId { get; set; }
        public Lanche Lanche { get; set; }

        public int Quantidade { get; set; }

        [StringLength(200)]
        public string CarrinhoCompraId { get; set; }
    }
}

Models/Categoria.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Lanchonete.Models
{

    [Table ("Categorias")]
    public class Categoria
    {

        [Key]
        public int CategoriaID { get; set; }

        [StringLength (100, ErrorMessage ="o tamanho máximo é 100 caracteres.")]
        [Required(ErrorMessage = "informe o nome da categoria.")]
        [Display(Name = "Nome")]
        public string CategoriaNome { get; set; }

        [StringLength(200, ErrorMessage = "o tamanho máximo é 200 caracteres.")]
        [Required(ErrorMessage = "informe a descrição da categoria.")]
        [Display(Name = "Nome")]
        public string Descricao { get; set; }

        public List<Lanche> Lanches { get; set; }
      
    }
}

    

Models/ErrorViewModel.cs
namespace Lanchonete.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Lanche.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Lanchonete.Models
{
    [Table("Lanches")]
    public class Lanche
    {
        [Key]
        public int LancheId { get; set; }

        //-------------------------------------------------------------

        [Required(ErrorMessage = "o nome do lanche deve ser informado!")]
        [Display(Name = "Nome do lanche")]
        [StringLength(80, MinimumLength = 10, ErrorMessage = " O {0} deve ter no mínimo {1} e no máximo {2} ")]                              
        public string Name { get; set; }

        //-------------------------------------------------------------

        [Required(ErrorMessage = "A descrição curta do lanche deve ser informado!")]
        [Display(Name = "Descrição curta do lanche")]
        [MinLength(20, ErrorMessage = " descrição curta deve ter no mínimo {1} caracteres. ")]
        [MaxLength(200, ErrorMessage = " descrição curta pode exceder {1} caracteres.")]
        public string DescricaoCurta { get; set; }

        //-------------------------------------------------------------

        [Required(ErrorMessage = "A descrição detalhada do lanche deve ser informado!")]
        [Display(Name = "Descrição detalhada do lanche")]
        [MinLength(20, ErrorMessage = " descrição detalhada deve ter no mínimo {1} caracteres. ")]
        [MaxLength(200, ErrorMessage = " descrição detalhada pode exceder {1} caracteres.")]
        public string  DescricaoDetalhada { get; set; }

        //-------------------------------------------------------------

        [Required(ErrorMessage = "informe o preço do lanche!")]
        [Display(Name = "preço")]
        [Column(TypeName = "decimal(10.2")]
        [Range(1, 999.99, ErrorMessage = "o preço deve estar entre $1 e $999,99")]
        public decimal Preco { get; set; }

        //-------------------------------------------------------------
        [Display(Name = "caminho imagem normal")]
        [StringLength(200, ErrorMessage = "o {0} deve ter no máximo {1} caracteres.")]
        public string ImagemUrl { get; set; }

        //-------------------------------------------------------------

        [Display(Name = "caminho imagem normal")]
        [StringLength(200, ErrorMessage = "o {0} deve ter no máximo {1} caracteres.")]
        public string ImagemThumbnailUrl { get; set; }

        //-------------------------------------------------------------

        [Display(Name = "preferido?")]
        public bool IsLanchePreferido { get; set; }

        //-------------------------------------------------------------

        [Display(Name = "em estoque?")]
        public bool EmEstoque { get; set; }





        public int CategoriaId { get; set;}
        public virtual Categoria Categoria { get; set; }
    }
}

ViewModels/LancheListViewModel.cs
using Lanchonete.Models;

namespace Lanchonete.ViewModels
{
    public class LancheListViewModel
    {
        public IEnumerable<Lanche> Lanches { get; set; }    
        public string CategoriaAtual {  get; set; }
    }
}

Controllers/HomeController.cs
using Lanchonete.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lanchonete.Controllers
{
    public class HomeController : Controller
    {
     
        public IActionResult Index()
        {
            TempData["Nome"] = "Janaina";
            return View();
        }


        public IActionResult Demo()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LancheController.cs
using Lanchonete.Repositories.Interfaces;
using Lanchonete.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Lanchonete.Controllers
{
    public class LancheController : Controller
    {
        private readonly ILancheRepository _lancheRepository;

        public LancheController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }

        public IActionResult List()
        {
            // ViewData["Titulo"] = "Todos os Lanches";
            // ViewData["Data"] = DateTime.Now;
            // var lanches = _lancheRepository.Lanches;
            // var totalLanches = lanches.Count();

            // ViewBag.Total = "Total de Lanches: ";
            // ViewBag.TotalLanches = totalLanches;

            //  return View(lanches);

            var lanchesListViewModel = new LancheListViewModel();
            lanchesListViewModel.Lanches = _lancheRepository.Lanches;
            lanchesListViewModel.CategoriaAtual = "Categoria atual";
            
            return View(lanchesListViewModel);
        }
    }
}

Views/Home/Demo.cshtml
<h2> olá mundo</h2>

Views/Home/Index.cshtml
<h1>View index</h1>

<partial name ="_Carousel"/>

Views/Lanche/List.cshtml
@model LancheListViewModel

<div>
    <!-- <h2>@ViewData["Titulo"]</h2> -->
    <h2>@Model.CategoriaAtual</h2>
</div>

<!--
//<h2>@ViewData["Data"]</h2>
<hr />
//<h3>@ViewBag.Total @ViewBag.TotalLanches</h3>
<hr />

<h3>@TempData["Nome"];</h3>
-->

<div class="container">
    <div class="row">
        @foreach(var lanche in Model.Lanches)
        {
            <partial name="_LanchesResumo" for="@lanche"/>
        }
    </div>
</div>

Views/Shared/_Carousel.cshtml
<div id="carouselSuculentas" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/img01.jpeg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/images/img02.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/imagens/img03.jpeg" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselSuculentas" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselSuculentas" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

Views/Shared/_LanchesResumo.cshtml
@model Lanche

<div class="col-sm-4 col-md-4 col-lg-4">
    <p><img src="@Model.ImagemUrl" class="img-fluid" /></p>
    <h3>Preço: @Model.Preco.ToString("c")</h3>
    <h4>@Model.Name</h4>
    <p>@Model.DescricaoCurta</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lanchonete</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lanchonete.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lanchonete</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lanche" asp-action="List">Lanches</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Lanchonete - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>